### ISSUE TITLE
The problems of the tools

### ISSUE THREAD

**Issue by OneMondy** [XingangPan/seg_label_generate#1]
Hi,xingang. I am a new person in this area.When I run this tool, I have some questions. Can you please help me  to solve it?.after i make the file of seg_label_generate,A problem occurred.

include/lane/util.hpp;FATAL ERROR:OPENCV2/CORE/CORE.HPP:no such file or directory.

thanks!

**Comment by XingangPan** [comment]
It seems that you need to successfully install Opencv 2.4.8 or later 2.4.x version.

**Comment by OneMondy** [comment]
Thank you for your answer!
