### ISSUE TITLE
How to get instance labeled image ?

### ISSUE THREAD

**Issue by BenBaek** [XingangPan/seg_label_generate#17]
Thanks for your work.
I want to check my network model on CULane benchmarks, so I download your dataset on google drive and follow your instruction.

I make a exe file and change directory path in labelGen.sh file, then I can see the labeled lane mask with source image.

I try to get segmented image without -s command in labelGen.sh, but I have got only black colored image.
Could you help me get the proper segmented image?
![00000](https://user-images.githubusercontent.com/39553764/71815279-8a8c0c00-30b1-11ea-8da8-ca802fc288fe.png)

**Comment by XingangPan** [comment]
The labels for the 4 lane markings are 1,2,3,4, so they look like black in the 0-255 png images.

**Comment by BenBaek** [comment]
> The labels for the 4 lane markings are 1,2,3,4, so they look like black in the 0-255 png images.

It works well.
Thank you very much.

**Comment by yuxuanhuang02** [comment]
hi,how can i use labelGen.sh to generate seglabel? when i run labelGen.sh, there always error,like opencv error.
