### ISSUE TITLE
Question about of existence ground truth of train_gt.txt

### ISSUE THREAD

**Issue by DanLiu0623** [XingangPan/seg_label_generate#7]
How to judge existence ground truth is '0' or '1', I refer https://github.com/XingangPan/seg_label_generate this repo but I can not understand code without any comments. So could you kindly let me know the ways to generate existence ground truth?

**Comment by XingangPan** [comment]
In the code, we first get the position of lanes according to their **slope**, then get the existence accordingly.
For example, if there are 3 lanes with slope that is (positive, positive, negative) from left to right, it means their are 2 lanes on the left and 1 lane on the right, then the existence ground truth would be (1,1,1,0).

**Comment by DanLiu0623** [comment]
@XingangPan  Ok, I see,Thank you very much.
