### ISSUE TITLE
opencv failure

### ISSUE THREAD

**Issue by zguo008** [XingangPan/seg_label_generate#9]
Hey xingang,

I have trouble compling the files after key in "make". They said I have undefined reference to CV. But I have installed CV sucessfully and tested with some simple programs.

I am using opencv 3.4. Based on your description, opencv 2.4 is recommended. 

May I know if it's version incompatabilty causes the undefined reference?

Best regards,

ZX

**Comment by XingangPan** [comment]
It is likely to be a version incompatabilty issue.
For opencv issue, I suggest to explore solutions on google or stackoverflow. Thanks.

**Comment by zguo008** [comment]
thank you very much:)
have a nice day ahead!
